kind: ConfigMap  
apiVersion: v1  
metadata:  
  name: hello-nokia-configmap 
  namespace: hello-nokia  
  labels:  
    app: hello-nokia  
data:  
  index.html: |
    <!DOCTYPE html>
    <html>
        <head>
            <title>Hello World</title>
        </head>
        <body>
            <p>Hi Nokia!</p>
        </body>
    </html>
